version: "3"

services:
  urban-eats-server:
    image: urban-eats-server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://<your-prod-mongo-url>:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  urban-eats:
    driver: bridge

volumes:
  mongo-data:
