version: "3"

services:
  urban-eats-server:
    image: urban-eats-server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  urban-eats:
    driver: bridge

volumes:
  mongo-data:
    driver: local
