version: "3"

services:
  urban-eats-server:
    image: hazrat17/urban-eats-server:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb+srv://<DB_USER>:<DB_PASSWORD>@cluster0.t04cp.mongodb.net/urban-eats?retryWrites=true&w=majority
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - urban-eats-server

volumes:
  mongo-data:
