name: Build and Deploy Urban Eats Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PRIVATE_KEY: ${{ secrets.RSA_KEY_FOR_APP_EC2 }}
  INSTANCE_IP: ${{ vars.INSTANCE_IP }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t urban-eats-server:latest .

      - name: Tag Docker image
        run: |
          docker tag urban-eats-server:latest ${{ secrets.DOCKER_USERNAME }}/urban-eats-server:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/urban-eats-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Copy docker-compose and nginx files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.RSA_KEY_FOR_APP_EC2 }}
          source: "docker-compose.production.yaml,nginx.conf"
          target: "~/"

      - name: SSH into EC2 and deploy Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.RSA_KEY_FOR_APP_EC2 }}
          script: |
            docker-compose -f docker-compose.production.yml up -d
            docker image prune -f
