name: Build and Deploy

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log into Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      # Run tests (if applicable)
      - name: Run tests
        run: |
          docker-compose up --exit-code-from urban-eats-server --abort-on-container-exit
        continue-on-error: false

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag urban-eats-server:latest ${{ secrets.DOCKER_USERNAME }}/urban-eats-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/urban-eats-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # SSH into server and deploy the app
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /path/to/deployment
            docker-compose down
            docker-compose pull
            docker-compose up -d
